version: '3'

services:
  db:
    image: mysql:5.7
    container_name: webappdb
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'OnlineJudge'
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py test"
    container_name: webapp
    volumes:
      - .:/CallOJ
    ports:
      - "8000:8000"
    depends_on:
      - db
