id: dmoj
key: dmoj

problem_storage_root:
  - /home/jayant/Desktop/Latest/CallOJ/media/problems

runtime:
  as_x64: /usr/bin/x86_64-linux-gnu-as
  as_x86: /usr/bin/as
  awk: /usr/bin/mawk
  cat: /bin/cat
  dmd: /snap/bin/dmd
  sed: /bin/sed
  tclsh: /usr/bin/tclsh
  ld_x64: /usr/bin/x86_64-linux-gnu-ld
  ld_x86: /usr/bin/ld
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++17: /usr/bin/g++-8
  java8: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  javac8: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  perl: /usr/bin/perl
  python: /usr/bin/python2.7
  python3: /usr/bin/python3.7
  


